name: Update Top Languages

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-top-langs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: pip install requests
      - name: Run the script
        env:
          GITHUB_TOKEN: ${{ secrets.TOP_LANGS_TOKEN }}
        run: python generate_top_languages.py > top_langs.md
      - name: Update README.md
        run: |
          awk '/<!-- START:generated-langs -->/{print; system("cat top_langs.md"); f=1; next} /<!-- END:generated-langs -->/{f=0} !f' README.md > README.new.md
          mv README.new.md README.md
      - name: Commit & Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update top languages (private included)"
          git push
